version: '2'
services:
  app:
    image: plaborderie/iut-notes
    ports:
      - 4000:4000
    environment: 
      - JWT_PRIVATE
      - JWT_PUBLIC
      - PG_DATABASE
      - PG_USERNAME
      - PG_PASSWORD
      - PG_HOST
      - PG_PORT
      - NODE_ENV
    depends_on: 
      - db
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_DB: ${PG_DATABASE}
    