# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: "Pull submodules"
          command: |
            git submodule init
            git submodule update --remote
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker build -t plaborderie/$IMAGE_NAME:0.1.${CIRCLE_BUILD_NUM} -t plaborderie/$IMAGE_NAME:latest .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker push plaborderie/$IMAGE_NAME:0.1.${CIRCLE_BUILD_NUM}
            docker push plaborderie/$IMAGE_NAME:latest
      - run:
          name: Deploy app to remote server
          command: |
            ssh -o StrictHostKeyChecking=no -fnL localhost:2374:/var/run/docker.sock ubuntu@52.210.74.124
            docker -H localhost:2374 stack deploy --with-registry-auth -c docker-stack.yml iut-notes