# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: "Pull submodules"
          command: |
            git submodule init
            git submodule update --remote
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker build -t plaborderie/$IMAGE_NAME:0.1.${CIRCLE_BUILD_NUM} .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker push plaborderie/$IMAGE_NAME:0.1.${CIRCLE_BUILD_NUM}
      - run:
          name: Deploy app to AWS
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@iut-notes.fr "bash ~/serve.sh"